#!/bin/bash
# Incognito OS Welcome Script

echo ""
echo "  ⚡ Incognito OS"
echo "  Fast. Private. Invisible."
echo ""
echo "  System Information:"
echo "  -----------------"
echo "  Hostname: $(hostname)"
echo "  Kernel: $(uname -r)"
echo "  Uptime: $(uptime -p)"
echo "  Memory: $(free -h | awk '/Mem:/ {print $3 "/" $2}')"
echo "  Disk: $(df -h / | awk 'NR==2 {print $3 "/" $2}')"
echo ""
echo "  Tor Status: $(if systemctl is-active --quiet tor; then echo "🟢 ON"; else echo "🔴 OFF"; fi)"
echo ""
echo "  Quick Commands:"
echo "  --------------"
echo "  startx       - Start desktop environment"
echo "  toggle-tor   - Toggle Tor ON/OFF"
echo "  htop         - System monitor"
echo "  nmap        - Network scanner"
echo "  firefox     - Web browser"
echo "  security-tools - Open security tools menu"
echo ""
echo "  Type 'menu' for application menu"
echo ""
